# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3bc2f86901619a9ef9b119a1a42a0cc36ea86185078316f42e431e7031c0aac7536389b2eb5d89e185a43f1681d7ee7ddec70ef22dc4265dc10205adeb091ea

test:
  secret_key_base: 96d92aaa3376b22aef22277ef05b08b041bb14feca6b789819d265394bb8c3ed854c0be3341f53fba93e3a91127037b68ee95b0ff583d8c7fcf678c9aeb44bba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
